In [106]:
import pandas as pd

data_row=pd.read_csv("/Users/withmocha/Desktop/DATA/Capston Design(2024)/Data(24.03.12)/data(use)/model train(already concat)/shuffle_data_sum.csv")

data_row

Unnamed: 0  word     predict
0           116342     년  No fishing
1            92425    유료  No fishing
2           119617    단순     fishing
3            80725    접수  No fishing
4            38425  홈페이지  No fishing
...            ...   ...         ...
209236       65678    금융     fishing
209237      149035     것  No fishing
209238      144267    누출     fishing
209239       99456   수사관     fishing
209240      174608    하나     fishing

[209241 rows x 3 columns]

In [107]:
data_row.isnull().sum()

Unnamed: 0    0
word          0
predict       0
dtype: int64

In [108]:
data_row.drop(columns=["Unnamed: 0"],inplace=True)

In [109]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [110]:
print(data_row.iloc[1,0]==data_row.iloc[2,0])

False


In [111]:
A=le.fit_transform(data_row['word'])

In [112]:
A.dtype

dtype('int64')

In [113]:
for i in range(data_row.shape[0]):
    data_row.iloc[i,0]=A[i]

In [114]:
data=data_row

In [115]:
A=le.fit_transform(data['predict'])

In [116]:
data

word     predict
0       1185  No fishing
1       4384  No fishing
2       1324     fishing
3       5159  No fishing
4       6804  No fishing
...      ...         ...
209236   864     fishing
209237   278  No fishing
209238  1267     fishing
209239  3306     fishing
209240  6519     fishing

[209241 rows x 2 columns]

In [117]:
A

array([0, 0, 1, ..., 1, 1, 1])

In [118]:
for i in range(data.shape[0]):
    data.iloc[i,1]=A[i]

In [119]:
data.columns

Index(['word', 'predict'], dtype='object')

In [120]:
data

word predict
0       1185       0
1       4384       0
2       1324       1
3       5159       0
4       6804       0
...      ...     ...
209236   864       1
209237   278       0
209238  1267       1
209239  3306       1
209240  6519       1

[209241 rows x 2 columns]

In [121]:
data.astype('int32').dtypes

word       int32
predict    int32
dtype: object

In [122]:
x_train=pd.DataFrame(data=data['word'],columns=['word'])

In [123]:
x_train

word
0       1185
1       4384
2       1324
3       5159
4       6804
...      ...
209236   864
209237   278
209238  1267
209239  3306
209240  6519

[209241 rows x 1 columns]

In [124]:

y_train=pd.DataFrame(data=data['predict'],columns=['predict'],copy=True)

In [125]:

y_train

predict
0            0
1            0
2            1
3            0
4            0
...        ...
209236       1
209237       0
209238       1
209239       1
209240       1

[209241 rows x 1 columns]

In [126]:

x_train.astype('int32').dtypes
y_train.astype('int32').dtypes


predict    int32
dtype: object

In [127]:
data=x_train

In [128]:
target=y_train

In [129]:
import numpy as np
from sklearn.model_selection import train_test_split

In [130]:
x_train['word']=x_train['word'].astype(float)
y_train['predict']=y_train['predict'].astype(float)

In [131]:
x_train,x_valid,y_train,y_valid=train_test_split(data,target,test_size=0.2,shuffle=True,stratify=target,random_state=34)

In [132]:
print(x_train.dtypes)
print(y_train.dtypes)
print(x_valid.dtypes)

word    float64
dtype: object
predict    float64
dtype: object
word    float64
dtype: object


In [133]:

from xgboost import XGBClassifier

# 모델 선언 예시
model = XGBClassifier()
model.fit(x_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, random_state=None, ...)

In [134]:
y_pred=model.predict(x_valid)

In [135]:
from sklearn.metrics import accuracy_score

In [136]:
print("XGBoost 보이스 피싱 탐지 정확도 : ", format(accuracy_score(y_valid,y_pred)*100))

XGBoost 보이스 피싱 탐지 정확도 :  71.90374919352912


In [137]:
test_data=pd.read_csv("/Users/withmocha/Desktop/DATA/Capston Design(2024)/Data(24.03.12)/data(use)/model train(already concat)/test_data.csv")

In [138]:
test_data

Unnamed: 0 word     predict
0          143905   목적  No fishing
1           20119   회원  No fishing
2             330    월  No fishing
3           49709   본인     fishing
4           81819    앱  No fishing
...           ...  ...         ...
41844      161730   인증     fishing
41845       17550    십     fishing
41846      143203   판단     fishing
41847       18544  신분증  No fishing
41848       66216    도     fishing

[41849 rows x 3 columns]

In [139]:
test_data.drop(columns=['Unnamed: 0'],inplace=True)

In [140]:
x_test=pd.DataFrame(data=test_data['word'],columns=['word'])

In [141]:
x_test

word
0       목적
1       회원
2        월
3       본인
4        앱
...    ...
41844   인증
41845    십
41846   판단
41847  신분증
41848    도

[41849 rows x 1 columns]

In [142]:
y_test=pd.DataFrame(data=test_data['predict'],columns=['predict'])

In [143]:
y_test

predict
0      No fishing
1      No fishing
2      No fishing
3         fishing
4      No fishing
...           ...
41844     fishing
41845     fishing
41846     fishing
41847  No fishing
41848     fishing

[41849 rows x 1 columns]

In [144]:
#le = LabelEncoder()

In [145]:
x_test=le.fit_transform(x_test['word'])
y_test=le.fit_transform(y_test['predict'])

In [146]:
x_test

array([1206, 4104, 2569, ..., 3783, 2133,  929])

In [147]:
y_test

array([0, 0, 0, ..., 1, 0, 1])

In [148]:
x_test=pd.DataFrame(data=x_test,columns=['word'])
y_test=pd.DataFrame(data=y_test,columns=['predict'])

In [149]:
x_test

word
0      1206
1      4104
2      2569
3      1552
4      2262
...     ...
41844  2796
41845  2191
41846  3783
41847  2133
41848   929

[41849 rows x 1 columns]

In [150]:
y_train

predict
66580       0.0
124787      1.0
95046       1.0
115200      0.0
30912       1.0
...         ...
184968      1.0
38776       0.0
192070      0.0
175698      1.0
171860      1.0

[167392 rows x 1 columns]

In [151]:
pred=model.predict(x_test)

In [152]:
pred=pd.DataFrame(data=pred,columns=['predict'])

In [153]:
pred

predict
0            0
1            0
2            1
3            1
4            0
...        ...
41844        0
41845        0
41846        1
41847        0
41848        1

[41849 rows x 1 columns]

In [154]:
y_test

predict
0            0
1            0
2            0
3            1
4            0
...        ...
41844        1
41845        1
41846        1
41847        0
41848        1

[41849 rows x 1 columns]

In [155]:
print("XGBoost 보이스 피싱 탐지 테스트 정확도 : ", format(accuracy_score(y_test,pred)*100))

XGBoost 보이스 피싱 탐지 테스트 정확도 :  49.451599799278355
