In [110]:
import pandas as pd

data_row=pd.read_csv("/Users/withmocha/Desktop/DATA/Capston Design(2024)/Data(24.03.12)/data(use)/data(small)/train/train_data_small.csv")

data_row

Unnamed: 0 word     predict
0           1168   기존     fishing
1            975    만     fishing
2            420   벌금  NO fishing
3            680   연령  NO fishing
4            409    앞  NO fishing
...          ...  ...         ...
1477         359   일자  NO fishing
1478         900   금융     fishing
1479        1178    밑     fishing
1480        1076   그때     fishing
1481         810  쓰레기  NO fishing

[1482 rows x 3 columns]

In [111]:
data_row.isnull().sum()

Unnamed: 0    0
word          0
predict       0
dtype: int64

In [112]:
data_row.drop(columns=["Unnamed: 0"],inplace=True)

In [113]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [114]:
print(data_row.iloc[1,0]==data_row.iloc[2,0])

False


In [115]:
A=le.fit_transform(data_row['word'])

In [116]:
A.dtype

dtype('int64')

In [117]:
for i in range(data_row.shape[0]):
    data_row.iloc[i,0]=A[i]

In [118]:
data=data_row

In [119]:
A=le.fit_transform(data['predict'])

In [120]:
data

word     predict
0     212     fishing
1     353     fishing
2     438  NO fishing
3     697  NO fishing
4     665  NO fishing
...   ...         ...
1477  826  NO fishing
1478  191     fishing
1479  404     fishing
1480  179     fishing
1481  646  NO fishing

[1482 rows x 2 columns]

In [121]:
A

array([1, 1, 0, ..., 1, 1, 0])

In [122]:
for i in range(data.shape[0]):
    data.iloc[i,1]=A[i]

In [123]:
data.columns

Index(['word', 'predict'], dtype='object')

import sklearn

from sklearn.preprocessing import MinMaxScaler

In [124]:
data

word predict
0     212       1
1     353       1
2     438       0
3     697       0
4     665       0
...   ...     ...
1477  826       0
1478  191       1
1479  404       1
1480  179       1
1481  646       0

[1482 rows x 2 columns]

In [125]:
from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()
data=pd.DataFrame(scaler.fit_transform(data),columns=['word','predict'])

In [127]:
data

word   predict
0    -1.129633  1.215838
1    -0.723307  1.215838
2    -0.478359 -0.822478
3     0.268012 -0.822478
4     0.175796 -0.822478
...        ...       ...
1477  0.639756 -0.822478
1478 -1.190150  1.215838
1479 -0.576339  1.215838
1480 -1.224730  1.215838
1481  0.121043 -0.822478

[1482 rows x 2 columns]

In [128]:
data.astype('int32').dtypes

word       int32
predict    int32
dtype: object

In [129]:
x_train=pd.DataFrame(data=data['word'],columns=['word'])

In [130]:
x_train

word
0    -1.129633
1    -0.723307
2    -0.478359
3     0.268012
4     0.175796
...        ...
1477  0.639756
1478 -1.190150
1479 -0.576339
1480 -1.224730
1481  0.121043

[1482 rows x 1 columns]

In [131]:

y_train=pd.DataFrame(data=data['predict'],columns=['predict'],copy=True)

In [132]:

y_train

predict
0     1.215838
1     1.215838
2    -0.822478
3    -0.822478
4    -0.822478
...        ...
1477 -0.822478
1478  1.215838
1479  1.215838
1480  1.215838
1481 -0.822478

[1482 rows x 1 columns]

In [133]:

x_train.astype('int32').dtypes
y_train.astype('int32').dtypes


predict    int32
dtype: object

In [134]:
data=x_train

In [135]:
target=y_train

In [136]:
import numpy as np
from sklearn.model_selection import train_test_split
x_train,x_valid,y_train,y_valid=train_test_split(data,target,test_size=0.2,shuffle=True,stratify=target)

In [137]:
x_train['word']=x_train['word'].astype(float)
y_train['predict']=y_train['predict'].astype(float)

In [138]:
data

word
0    -1.129633
1    -0.723307
2    -0.478359
3     0.268012
4     0.175796
...        ...
1477  0.639756
1478 -1.190150
1479 -0.576339
1480 -1.224730
1481  0.121043

[1482 rows x 1 columns]

In [139]:
target

predict
0     1.215838
1     1.215838
2    -0.822478
3    -0.822478
4    -0.822478
...        ...
1477 -0.822478
1478  1.215838
1479  1.215838
1480  1.215838
1481 -0.822478

[1482 rows x 1 columns]

In [140]:
print(data.dtypes)
print(target.dtypes)

word    float64
dtype: object
predict    float64
dtype: object


In [141]:
from keras.layers import LSTM 
from keras.models import Sequential 
from keras.layers import Dense 

# 모델 선언 예시
model = Sequential() 
# 첫번째 LSTM 레이어
model.add(LSTM(30,return_sequences=True, input_shape=(data.shape[0], 1))) 
# 두번째 LSTM 레이어
model.add(LSTM(42,return_sequences=False))  
# 예측값 1개
model.add(Dense(1, activation='linear')) 
# 손실함수 지정 - 예측 값과 실제 값의 차이를 계산한다. MSE가 사용된다. 
# 최적화기 지정 - 일반적으로 adam을 사용한다.
model.compile(loss='mean_squared_error', optimizer='adam') 
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_6 (LSTM)               (None, 1482, 30)          3840      
                                                                 
 lstm_7 (LSTM)               (None, 42)                12264     
                                                                 
 dense_3 (Dense)             (None, 1)                 43        
                                                                 
Total params: 16,147
Trainable params: 16,147
Non-trainable params: 0
_________________________________________________________________


2024-03-30 16:32:48.181170: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_2_grad/concat/split_2/split_dim' with dtype int32
	 [[{{node gradients/split_2_grad/concat/split_2/split_dim}}]]
2024-03-30 16:32:48.181954: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_grad/concat/split/split_dim' with dtype int32
	 [[{{node gradients/split_grad/concat/split/split_dim}}]]
2024-03-30 16:32:48.182421: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You mus

In [142]:
model.fit(data,target,epochs=1000)


Epoch 1/1000


2024-03-30 16:32:48.668194: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_2_grad/concat/split_2/split_dim' with dtype int32
	 [[{{node gradients/split_2_grad/concat/split_2/split_dim}}]]
2024-03-30 16:32:48.669028: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_grad/concat/split/split_dim' with dtype int32
	 [[{{node gradients/split_grad/concat/split/split_dim}}]]
2024-03-30 16:32:48.669652: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You mus

47/47 [==============================] - 1s 1ms/step - loss: 1.0008
Epoch 2/1000
47/47 [==============================] - 0s 1ms/step - loss: 1.0004
Epoch 3/1000
47/47 [==============================] - 0s 924us/step - loss: 1.0004
Epoch 4/1000
47/47 [==============================] - 0s 870us/step - loss: 1.0004
Epoch 5/1000
47/47 [==============================] - 0s 874us/step - loss: 1.0001
Epoch 6/1000
47/47 [==============================] - 0s 861us/step - loss: 1.0003
Epoch 7/1000
47/47 [==============================] - 0s 866us/step - loss: 1.0002
Epoch 8/1000
47/47 [==============================] - 0s 888us/step - loss: 1.0002
Epoch 9/1000
47/47 [==============================] - 0s 869us/step - loss: 1.0002
Epoch 10/1000
47/47 [==============================] - 0s 853us/step - loss: 1.0000
Epoch 11/1000
47/47 [==============================] - 0s 962us/step - loss: 1.0000
Epoch 12/1000
47/47 [==============================] - 0s 957us/step - loss: 1.0002
Epoch 13/1000
47/4

In [143]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score

In [149]:
y_pred=pd.DataFrame(model.predict(x_valid),columns=['predict'])

10/10 [==============================] - 0s 556us/step


In [150]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score

In [151]:
y_pred

predict
0   -0.066455
1   -0.045364
2    0.046195
3    0.024069
4    0.018523
..        ...
292 -0.007906
293  0.078058
294  0.037054
295  0.001924
296  0.077352

[297 rows x 1 columns]

In [152]:
y_valid

predict
200  -0.822478
246   1.215838
438  -0.822478
1245 -0.822478
677   1.215838
...        ...
48    1.215838
1031  1.215838
57   -0.822478
249   1.215838
1062 -0.822478

[297 rows x 1 columns]

In [154]:
print("XGBoost 보이스 피싱 탐지 정확도 : ", format(accuracy_score(y_valid,y_pred)*100))

ValueError: continuous is not supported

In [48]:
test_data=pd.read_csv("/Users/withmocha/Desktop/DATA/Capston Design(2024)/Data(24.03.12)/data(use)/data(small)/test/test_data_small.csv")

In [49]:
test_data

Unnamed: 0 word     predict
0             0   상시  NO fishing
1             1   우편  NO fishing
2             2   요금  NO fishing
3             3   근거     fishing
4             4   구분  NO fishing
..          ...  ...         ...
195         195   세탁     fishing
196         196   실업  NO fishing
197         197   맹점  NO fishing
198         198   걸로  NO fishing
199         199    십     fishing

[200 rows x 3 columns]

In [50]:
test_data.drop(columns=['Unnamed: 0'],inplace=True)

In [51]:
x_test=pd.DataFrame(data=test_data['word'],columns=['word'])

In [52]:
x_test

word
0     상시
1     우편
2     요금
3     근거
4     구분
..   ...
195   세탁
196   실업
197   맹점
198   걸로
199    십

[200 rows x 1 columns]

In [53]:
y_test=pd.DataFrame(data=test_data['predict'],columns=['predict'])

In [54]:
y_test

predict
0    NO fishing
1    NO fishing
2    NO fishing
3       fishing
4    NO fishing
..          ...
195     fishing
196  NO fishing
197  NO fishing
198  NO fishing
199     fishing

[200 rows x 1 columns]

In [55]:
#le = LabelEncoder()

In [56]:
x_test=le.fit_transform(x_test['word'])
y_test=le.fit_transform(y_test['predict'])

In [57]:
x_test

array([ 90, 115, 114,  32,  24,  13,  10, 109, 173, 184,  38,  25,  47,
       121,  27,  41,  36, 162,  39,  44,  18,  26,  82,  77,  85, 125,
       171, 116, 148, 157,  37,  60, 179,  22,  28,  57, 146, 118,  59,
        75, 131, 130,  78, 170,  94,  78,  86,  68,  87,  63, 121,  72,
       163,  76, 181, 129, 169,   0, 178, 124,  95, 182,  89,  91, 184,
        97, 102,  30,   7, 172, 152,   5,  64,  34, 180,  12, 117,   4,
       119,  54,  52,  79, 101, 174, 110, 133, 159,  42, 164,   2, 134,
         1,  67, 157,  46,  19,   9, 166, 104,  45,   6, 155, 168,  23,
        11, 135,  43, 154,  93,  47,  48, 140,  14, 145, 137, 147,  20,
       161,  70, 143,  69,   8,  38, 132,  97, 177,   6, 113, 120,  74,
       111,  65, 144,  99, 150, 103, 142,  73,  15,  49,  58,  51,  40,
       139, 136,  96, 151, 167, 149, 183, 122, 127, 185,  35, 138,  55,
         5, 107, 112, 153, 123, 141,  71,  33,  98,  80,  58,  16,  53,
        50,  81,  29, 108, 108,  88,  84,  61,  21, 165, 160, 10

In [58]:
y_test

array([0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1])

In [59]:
x_test=pd.DataFrame(data=x_test,columns=['word'])
y_test=pd.DataFrame(data=y_test,columns=['predict'])

In [60]:
x_test

word
0      90
1     115
2     114
3      32
4      24
..    ...
195    92
196   105
197    56
198    17
199   106

[200 rows x 1 columns]

In [61]:
y_train

predict
1002      0.0
1007      0.0
1122      0.0
986       1.0
43        0.0
...       ...
324       0.0
706       1.0
611       0.0
654       0.0
1457      0.0

[1185 rows x 1 columns]

In [62]:
y_pred=model.predict(y_test)

2024-03-30 16:24:11.358687: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_2_grad/concat/split_2/split_dim' with dtype int32
	 [[{{node gradients/split_2_grad/concat/split_2/split_dim}}]]
2024-03-30 16:24:11.359555: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_grad/concat/split/split_dim' with dtype int32
	 [[{{node gradients/split_grad/concat/split/split_dim}}]]
2024-03-30 16:24:11.360136: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You mus

7/7 [==============================] - 0s 657us/step


In [65]:
x_pred=model.predict(x_test)

1/7 [===>..........................] - ETA: 0s

7/7 [==============================] - 0s 3ms/step


In [66]:
x_pred

array([[ 0.4396323 ],
       [ 0.42477688],
       [ 0.4252609 ],
       [ 0.43308488],
       [ 0.4233192 ],
       [ 0.3996392 ],
       [ 0.2759482 ],
       [ 0.4278197 ],
       [ 0.4087285 ],
       [ 0.40743154],
       [ 0.44390404],
       [ 0.4237807 ],
       [ 0.45554093],
       [ 0.42206067],
       [ 0.42551562],
       [ 0.44866273],
       [ 0.44038433],
       [ 0.41040945],
       [ 0.44557142],
       [ 0.45257849],
       [ 0.4256708 ],
       [ 0.42452234],
       [ 0.44537133],
       [ 0.44899073],
       [ 0.4431931 ],
       [ 0.42042163],
       [ 0.40900278],
       [ 0.42430198],
       [ 0.41327196],
       [ 0.41132805],
       [ 0.44217032],
       [ 0.45845386],
       [ 0.40797937],
       [ 0.4232989 ],
       [ 0.42672804],
       [ 0.45896703],
       [ 0.41376054],
       [ 0.42337906],
       [ 0.45868602],
       [ 0.45040497],
       [ 0.41820306],
       [ 0.41855368],
       [ 0.4482735 ],
       [ 0.40914488],
       [ 0.43689114],
       [ 0

In [47]:
pred=pd.DataFrame(data=pred,columns=['predict'])

In [48]:
pred

predict
0          0
1          0
2          0
3          0
4          0
..       ...
195        1
196        0
197        0
198        0
199        0

[200 rows x 1 columns]

In [49]:
y_test

predict
0          0
1          0
2          0
3          1
4          0
..       ...
195        1
196        0
197        0
198        0
199        1

[200 rows x 1 columns]

In [50]:
print("XGBoost 보이스 피싱 탐지 테스트 정확도 : ", format(accuracy_score(y_test,pred)*100))

XGBoost 보이스 피싱 탐지 테스트 정확도 :  57.99999999999999


In [51]:
print(f1_score(y_test, pred, zero_division=1.0))

0.3731343283582089
