In [206]:
import pandas as pd

data=pd.read_csv("/Users/withmocha/Desktop/DATA/Capston Design(2024)/Data(24.03.12)/data(use)/model train(already concat)/shuffle_data_sum.cev")

data

Unnamed: 0  단어     predict
0            23851   번     fishing
1            72973  우리     fishing
2            84418  신청  No fishing
3            16103  발송     fishing
4            88009  세액  No fishing
...            ...  ..         ...
209236       87541  사람     fishing
209237       15486   말     fishing
209238       65813   줌  No fishing
209239      105122  효과  No fishing
209240       52419  청년  No fishing

[209241 rows x 3 columns]

In [207]:
data.isnull().sum()

Unnamed: 0    0
단어            0
predict       0
dtype: int64

In [208]:
data.drop(columns=["Unnamed: 0"],inplace=True)

In [209]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [210]:
print(data.iloc[1,0]==data.iloc[2,0])

False


In [211]:
A=le.fit_transform(data['단어'])

In [212]:
A.dtype

dtype('int64')

In [213]:
for i in range(data.shape[0]):
    data.iloc[i,0]=A[i]

In [214]:
data

단어     predict
0       2339     fishing
1       4222     fishing
2       3569  No fishing
3       2236     fishing
4       3127  No fishing
...      ...         ...
209236  2742     fishing
209237  1825     fishing
209238  5441  No fishing
209239  6917  No fishing
209240  5792  No fishing

[209241 rows x 2 columns]

In [215]:
A=le.fit_transform(data['predict'])

In [216]:
data

단어     predict
0       2339     fishing
1       4222     fishing
2       3569  No fishing
3       2236     fishing
4       3127  No fishing
...      ...         ...
209236  2742     fishing
209237  1825     fishing
209238  5441  No fishing
209239  6917  No fishing
209240  5792  No fishing

[209241 rows x 2 columns]

In [217]:
A

array([1, 1, 0, ..., 0, 0, 0])

In [218]:
A

array([1, 1, 0, ..., 0, 0, 0])

In [219]:
for i in range(data.shape[0]):
    data.iloc[i,1]=A[i]

In [220]:
data.columns

Index(['단어', 'predict'], dtype='object')

In [221]:
data['단어']

0         2339
1         4222
2         3569
3         2236
4         3127
          ... 
209236    2742
209237    1825
209238    5441
209239    6917
209240    5792
Name: 단어, Length: 209241, dtype: object

In [222]:
data.astype('int32').dtypes

단어         int32
predict    int32
dtype: object

In [223]:
x_train=pd.DataFrame(index=range(0,data.shape[0]),columns=['word'])

In [224]:
x_train

word
0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
...     ...
209236  NaN
209237  NaN
209238  NaN
209239  NaN
209240  NaN

[209241 rows x 1 columns]

In [225]:
for i in range(data.shape[0]):
    x_train.iloc[i,0]=data.iloc[i,0]

In [226]:
x_train

word
0       2339
1       4222
2       3569
3       2236
4       3127
...      ...
209236  2742
209237  1825
209238  5441
209239  6917
209240  5792

[209241 rows x 1 columns]

In [227]:

y_train=pd.DataFrame(data=data['predict'],columns=['predict'],copy=True)

In [228]:

y_train

predict
0            1
1            1
2            0
3            1
4            0
...        ...
209236       1
209237       1
209238       0
209239       0
209240       0

[209241 rows x 1 columns]

In [229]:
x_train.astype('int32').dtypes
y_train.astype('int32').dtypes


predict    int32
dtype: object

In [230]:
x_train['word']=x_train['word'].astype(float)
y_train['predict']=y_train['predict'].astype(float)

In [231]:
x_train.dtypes

word    float64
dtype: object

In [232]:
data=x_train

In [233]:
target=y_train

In [234]:
import numpy as np
from sklearn.model_selection import train_test_split

In [235]:
x_train,x_valid,y_train,y_valid=train_test_split(data,target,test_size=0.2,shuffle=True,stratify=target,random_state=34)

In [236]:
print(x_train.shape)
print(y_train.shape)
print(x_valid.shape)

(167392, 1)
(167392, 1)
(41849, 1)


In [237]:
import numpy
from keras.layers.core import Dense, Activation, Dropout
from tensorflow.keras.layers import LSTM
from keras.models import Sequential
import matplotlib.pyplot as plt
from keras.layers import Embedding, LSTM, Dense, Dropout


In [255]:
embedding_size=32
max_words=5000

model = Sequential()
model.add(LSTM(138, activation='sigmoid',return_sequences=True, input_shape=(x_train.shape[1], 1)))
model.add(LSTM(70,return_sequences=False))  
model.add(Dense(1, activation='linear'))
model.compile(loss='mse', optimizer='adam')
model.summary()

Model: "sequential_18"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_22 (LSTM)              (None, 1, 138)            77280     
                                                                 
 lstm_23 (LSTM)              (None, 70)                58520     
                                                                 
 dense_8 (Dense)             (None, 1)                 71        
                                                                 
Total params: 135,871
Trainable params: 135,871
Non-trainable params: 0
_________________________________________________________________


2024-03-26 21:44:18.559481: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_2_grad/concat/split_2/split_dim' with dtype int32
	 [[{{node gradients/split_2_grad/concat/split_2/split_dim}}]]
2024-03-26 21:44:18.560717: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_grad/concat/split/split_dim' with dtype int32
	 [[{{node gradients/split_grad/concat/split/split_dim}}]]
2024-03-26 21:44:18.561168: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You mus

In [256]:
model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

In [257]:
print(x_train.shape)
print(y_train.shape)

(167392, 1)
(167392, 1)


In [258]:
model.fit(x_train,y_train,epochs=1000,verbose=2,batch_size=32,steps_per_epoch=8)
pred=model.predict(x_valid)
pred

Epoch 1/1000


2024-03-26 21:44:25.713906: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_2_grad/concat/split_2/split_dim' with dtype int32
	 [[{{node gradients/split_2_grad/concat/split_2/split_dim}}]]
2024-03-26 21:44:25.714707: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_grad/concat/split/split_dim' with dtype int32
	 [[{{node gradients/split_grad/concat/split/split_dim}}]]
2024-03-26 21:44:25.715392: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You mus

8/8 - 1s - loss: 5.4948e-08 - accuracy: 0.5391 - 1s/epoch - 126ms/step
Epoch 2/1000
8/8 - 0s - loss: 5.9605e-08 - accuracy: 0.5000 - 12ms/epoch - 1ms/step
Epoch 3/1000
8/8 - 0s - loss: 5.8673e-08 - accuracy: 0.5078 - 14ms/epoch - 2ms/step
Epoch 4/1000
8/8 - 0s - loss: 6.0536e-08 - accuracy: 0.4922 - 11ms/epoch - 1ms/step
Epoch 5/1000
8/8 - 0s - loss: 6.0070e-08 - accuracy: 0.4961 - 11ms/epoch - 1ms/step
Epoch 6/1000
8/8 - 0s - loss: 5.5414e-08 - accuracy: 0.5352 - 10ms/epoch - 1ms/step
Epoch 7/1000
8/8 - 0s - loss: 5.4017e-08 - accuracy: 0.5469 - 10ms/epoch - 1ms/step
Epoch 8/1000
8/8 - 0s - loss: 5.4948e-08 - accuracy: 0.5391 - 12ms/epoch - 1ms/step
Epoch 9/1000
8/8 - 0s - loss: 6.2864e-08 - accuracy: 0.4727 - 13ms/epoch - 2ms/step
Epoch 10/1000
8/8 - 0s - loss: 5.9139e-08 - accuracy: 0.5039 - 12ms/epoch - 2ms/step
Epoch 11/1000
8/8 - 0s - loss: 5.8673e-08 - accuracy: 0.5078 - 10ms/epoch - 1ms/step
Epoch 12/1000
8/8 - 0s - loss: 5.5414e-08 - accuracy: 0.5352 - 13ms/epoch - 2ms/step
Ep

2024-03-26 21:44:42.376485: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_2_grad/concat/split_2/split_dim' with dtype int32
	 [[{{node gradients/split_2_grad/concat/split_2/split_dim}}]]
2024-03-26 21:44:42.377166: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_grad/concat/split/split_dim' with dtype int32
	 [[{{node gradients/split_grad/concat/split/split_dim}}]]
2024-03-26 21:44:42.377895: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You mus

1308/1308 [==============================] - 1s 504us/step


array([[0.18022834],
       [0.17658821],
       [0.176506  ],
       ...,
       [0.17799807],
       [0.18204394],
       [0.17858338]], dtype=float32)

In [259]:
performance = model.evaluate(y_valid, pred)
LSTM_acc=performance[1]*100

  95/1308 [=>............................] - ETA: 0s - loss: 2.1137e-08 - accuracy: 0.0000e+00  

2024-03-26 21:44:48.782448: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_2_grad/concat/split_2/split_dim' with dtype int32
	 [[{{node gradients/split_2_grad/concat/split_2/split_dim}}]]
2024-03-26 21:44:48.783069: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_grad/concat/split/split_dim' with dtype int32
	 [[{{node gradients/split_grad/concat/split/split_dim}}]]
2024-03-26 21:44:48.783512: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You mus

1308/1308 [==============================] - 1s 621us/step - loss: 2.1136e-08 - accuracy: 0.0000e+00


In [260]:
print('Test accuracy: ', LSTM_acc, '%')

Test accuracy:  0.0 %


In [204]:
y_valid

predict
143739      0.0
19781       0.0
321         0.0
49992       1.0
82119       0.0
...         ...
162107      1.0
17816       1.0
143425      1.0
18262       0.0
66197       1.0

[41849 rows x 1 columns]

In [205]:
pred

array([[1.],
       [1.],
       [1.],
       ...,
       [1.],
       [1.],
       [1.]], dtype=float32)