In [59]:
import pandas as pd

data_row=pd.read_csv("/Users/withmocha/Desktop/DATA/Capston Design(2024)/Data(24.03.12)/data(use)/model train(already concat)/shuffle_data_sum.csv")

data_row

Unnamed: 0  word     predict
0           116342     년  No fishing
1            92425    유료  No fishing
2           119617    단순     fishing
3            80725    접수  No fishing
4            38425  홈페이지  No fishing
...            ...   ...         ...
209236       65678    금융     fishing
209237      149035     것  No fishing
209238      144267    누출     fishing
209239       99456   수사관     fishing
209240      174608    하나     fishing

[209241 rows x 3 columns]

In [60]:
data_row.isnull().sum()

Unnamed: 0    0
word          0
predict       0
dtype: int64

In [61]:
data_row.drop(columns=["Unnamed: 0"],inplace=True)

In [62]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [63]:
print(data_row.iloc[1,0]==data_row.iloc[2,0])

False


In [64]:
A=le.fit_transform(data_row['word'])

In [65]:
A.dtype

dtype('int64')

In [66]:
for i in range(data_row.shape[0]):
    data_row.iloc[i,0]=A[i]

In [67]:
data=data_row

In [68]:
A=le.fit_transform(data['predict'])

In [69]:
data

word     predict
0       1185  No fishing
1       4384  No fishing
2       1324     fishing
3       5159  No fishing
4       6804  No fishing
...      ...         ...
209236   864     fishing
209237   278  No fishing
209238  1267     fishing
209239  3306     fishing
209240  6519     fishing

[209241 rows x 2 columns]

In [70]:
A

array([0, 0, 1, ..., 1, 1, 1])

In [71]:
for i in range(data.shape[0]):
    data.iloc[i,1]=A[i]

In [72]:
data.columns

Index(['word', 'predict'], dtype='object')

In [73]:
data

word predict
0       1185       0
1       4384       0
2       1324       1
3       5159       0
4       6804       0
...      ...     ...
209236   864       1
209237   278       0
209238  1267       1
209239  3306       1
209240  6519       1

[209241 rows x 2 columns]

In [74]:
data.astype('int32').dtypes

word       int32
predict    int32
dtype: object

In [75]:
x_train=pd.DataFrame(data=data['word'],columns=['word'])

In [76]:
x_train

word
0       1185
1       4384
2       1324
3       5159
4       6804
...      ...
209236   864
209237   278
209238  1267
209239  3306
209240  6519

[209241 rows x 1 columns]

In [77]:

y_train=pd.DataFrame(data=data['predict'],columns=['predict'],copy=True)

In [78]:

y_train

predict
0            0
1            0
2            1
3            0
4            0
...        ...
209236       1
209237       0
209238       1
209239       1
209240       1

[209241 rows x 1 columns]

In [79]:

x_train.astype('int32').dtypes
y_train.astype('int32').dtypes


predict    int32
dtype: object

In [80]:
from sklearn.preprocessing import MinMaxScaler


scaler=MinMaxScaler()

x_train=scaler.fit_transform(x_train)
y_train=scaler.fit_transform(y_train)

In [82]:
x_train

array([[0.16989247],
       [0.62853047],
       [0.18982079],
       ...,
       [0.18164875],
       [0.47397849],
       [0.93462366]])

In [83]:
y_train

array([[0.],
       [0.],
       [1.],
       ...,
       [1.],
       [1.],
       [1.]])

In [22]:
data=x_train

In [23]:
target=y_train

In [84]:
import numpy as np
from sklearn.model_selection import train_test_split

In [25]:
x_train['word']=x_train['word'].astype(float)
y_train['predict']=y_train['predict'].astype(float)

In [85]:
x_train,x_test,y_train,y_test=train_test_split(data,target,test_size=0.2,shuffle=True,stratify=target,random_state=34)

In [86]:
print(x_train.dtypes)
print(y_train.dtypes)


word       object
predict    object
dtype: object
predict    float64
dtype: object


In [87]:
x_train=np.array(x_train)
x_train=x_train.reshape(x_train.shape[0],x_train.shape[1],1)
x_train.shape

(167392, 2, 1)

In [28]:
from keras.models import Sequential
from keras.layers import Dense
from keras.callbacks import EarlyStopping, ModelCheckpoint
from keras.layers import LSTM
from tensorflow.keras import layers
from keras.layers import Activation, Dense
import tensorflow as tf 
from tensorflow.keras import Model
from keras.layers import Dropout
from keras.layers import Dense, Input, TimeDistributed, Flatten
from keras.layers.convolutional import Conv1D ,MaxPooling1D
from keras.optimizers import adam
from keras.models import Sequential
from keras.layers import Dense
from keras.callbacks import EarlyStopping, ModelCheckpoint
from keras.layers import LSTM
from keras.layers import Bidirectional
import numpy as np
from keras.applications import MobileNet
from sklearn.metrics import mean_squared_error
from keras.layers import Dense
from keras.callbacks import EarlyStopping, ModelCheckpoint
from keras.layers import LSTM
from tensorflow.keras import layers
from keras.layers import Activation, Dense
import tensorflow as tf 
from tensorflow.keras import Model
from keras.layers import Dropout
from keras.layers import Dense, Input, TimeDistributed, Flatten
from keras.layers.convolutional import Conv1D ,MaxPooling1D, AveragePooling1D
from keras.optimizers import adam
from keras.models import Sequential
from keras.layers import Dense
from keras.callbacks import EarlyStopping, ModelCheckpoint
from keras.layers import LSTM
from keras.layers import Bidirectional
import numpy as np
from keras.applications import MobileNet


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 time_distributed (TimeDistr  (None, None, 167392, 124  248      
 ibuted)                     )                                   
                                                                 
 time_distributed_1 (TimeDis  (None, None, 167392, 129  16125    
 tributed)                   )                                   
                                                                 
 time_distributed_2 (TimeDis  (None, None, 167392, 129  0        
 tributed)                   )                                   
                                                                 
 time_distributed_3 (TimeDis  (None, None, 21593568)   0         
 tributed)                                                       
                                                                 
 time_distributed_4 (TimeDis  (None, None, 122)        2

In [88]:
model_cnnbilstm = Sequential()
model_cnnbilstm.add(TimeDistributed(Conv1D(filters=124, kernel_size=1, activation='relu'), input_shape=(None,x_train.shape[1], x_train.shape[2])))
model_cnnbilstm.add(TimeDistributed(Conv1D(filters=129, kernel_size=1, activation='relu')))
model_cnnbilstm.add(TimeDistributed(MaxPooling1D(pool_size=1)))
model_cnnbilstm.add(TimeDistributed(Flatten()))
model_cnnbilstm.add(TimeDistributed(Dense(122, activation='relu',kernel_initializer = 'uniform',input_dim=10)))
model_cnnbilstm.add(Bidirectional(LSTM(113, return_sequences=True,activation='relu')))
model_cnnbilstm.add(Bidirectional(LSTM(178, return_sequences=True,activation='relu')))
model_cnnbilstm.add(Bidirectional(LSTM(228, return_sequences=True,activation='relu')))
#model_cnnbilstm.add(Bidirectional(LSTM(120, return_sequences=True,activation='relu')))
#model_cnnbilstm.add(Bidirectional(LSTM(170, return_sequences=True,activation='relu')))
model_cnnbilstm.add(TimeDistributed(Dense(156, activation='relu',kernel_initializer = 'uniform',input_dim=3)))
model_cnnbilstm.add(TimeDistributed(Dense(177, activation='relu',kernel_initializer = 'uniform',input_dim=1)))
#model_cnnbilstm.add(TimeDistributed(Dense(115, activation='relu',kernel_initializer = 'uniform',input_dim=10)))
#model_cnnbilstm.add(TimeDistributed(Dense(dense_par3, activation='relu',kernel_initializer = 'uniform',input_dim=dim4)))
#model_cnnbilstm.add(TimeDistributed(Dense(dense_par4, activation='relu',kernel_initializer = 'uniform',input_dim=dim5)))
model_cnnbilstm.add(TimeDistributed(Flatten()))
model_cnnbilstm.add(Dense(1))
model_cnnbilstm.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model_cnnbilstm.summary()


Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 time_distributed_24 (TimeDi  (None, None, 2, 124)     248       
 stributed)                                                      
                                                                 
 time_distributed_25 (TimeDi  (None, None, 2, 129)     16125     
 stributed)                                                      
                                                                 
 time_distributed_26 (TimeDi  (None, None, 2, 129)     0         
 stributed)                                                      
                                                                 
 time_distributed_27 (TimeDi  (None, None, 258)        0         
 stributed)                                                      
                                                                 
 time_distributed_28 (TimeDi  (None, None, 122)       

AttributeError: 'numpy.ndarray' object has no attribute 'dtypes'

In [91]:


model_cnnbilstm.fit(x_train,y_train,epochs=1000,verbose=2,batch_size=175,steps_per_epoch=6)

ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type numpy.int64).

In [52]:
x_test=np.array(x_test)
x_test=x_test.reshape(x_test.shape[0],x_test.shape[1],1)
x_test.shape

(41849, 1, 1)

In [53]:
y_pred=model_cnnbilstm.predict(x_test)

1308/1308 [==============================] - 3s 2ms/step


In [41]:
from sklearn.metrics import accuracy_score

In [58]:
y_pred

array([[[-0.01772233]],

       [[-0.13805781]],

       [[-0.07008731]],

       ...,

       [[-0.12214814]],

       [[-0.05069467]],

       [[-0.01239073]]], dtype=float32)

In [55]:
y_test=np.array(y_test)
y_test=x_test.reshape(y_test.shape[0],y_test.shape[1],1)
y_test.shape

(41849, 1, 1)

In [57]:

scores = model_cnnbilstm.evaluate(x_test, y_test, verbose=0)
print("Accuracy: %.2f%%" % (scores[1]*100))

Accuracy: 0.01%


In [32]:
test_data=pd.read_csv("/Users/withmocha/Desktop/DATA/Capston Design(2024)/Data(24.03.12)/data(use)/model train(already concat)/test_smalldata.csv")

In [33]:
test_data

Unnamed: 0 word     predict
0             0   회수  No fishing
1             1  시스템  No fishing
2             2  서울시  No fishing
3             3  지방세  No fishing
4             4   한계  No fishing
..          ...  ...         ...
195         195   부심  No fishing
196         196   가능  No fishing
197         197   정도     fishing
198         198   출력  No fishing
199         199   카드     fishing

[200 rows x 3 columns]

In [34]:
test_data.drop(columns=['Unnamed: 0'],inplace=True)

In [35]:
x_test=pd.DataFrame(data=test_data['word'],columns=['word'])

In [36]:
x_test

word
0     회수
1    시스템
2    서울시
3    지방세
4     한계
..   ...
195   부심
196   가능
197   정도
198   출력
199   카드

[200 rows x 1 columns]

In [37]:
y_test=pd.DataFrame(data=test_data['predict'],columns=['predict'])

In [38]:
y_test

predict
0    No fishing
1    No fishing
2    No fishing
3    No fishing
4    No fishing
..          ...
195  No fishing
196  No fishing
197     fishing
198  No fishing
199     fishing

[200 rows x 1 columns]

In [39]:
#le = LabelEncoder()

In [40]:
x_test=le.fit_transform(x_test['word'])
y_test=le.fit_transform(y_test['predict'])

In [41]:
x_test

array([160,  88,  81, 129, 154, 116,  51, 157,  61,   2,  39, 133, 151,
        70,  27,  40, 122,  48, 153,  47, 113,  35,  23,  86,  11,  85,
        49,   6, 134,  80,  54,  75,  28,  62,  71,  94, 104,   8,  95,
        82, 152, 107,  23, 106,  85, 146, 162,  79, 116,   0,  65,   6,
       129, 144, 139,  70,   0,  60,  57,  89,   4, 112,  16, 145,  52,
         6,  50,  93, 117,   6,  21,  67,  32,  15, 119,  98, 111, 119,
        96,   7,  76,  22,  91, 110,  29,  26,  30, 135, 108,  20,  78,
       115,  56,   6, 132,  64,  68, 116, 152,   8, 125,  97,  69,  36,
        33, 143, 127,  74,  83,  87,  70, 131,  80,   6,  58, 116, 159,
       120, 101,  18, 147, 153,  25, 131, 126,  59,  34, 141, 102,  41,
        43,   6,   0,  99, 108,  63, 128,  46,  72,  42,   3, 100, 105,
         1,  55,   5,  53,  84,  94, 116, 152,  90,  72, 124, 136,  12,
        63, 114,  24,  21, 150,  44, 130,   9,  94,  85,  65,  14, 115,
        77,  10,  37,  52,  73, 155,  31, 140, 158, 109, 156, 16

In [42]:
y_test

array([0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1])

In [43]:
x_test=pd.DataFrame(data=x_test,columns=['word'])
y_test=pd.DataFrame(data=y_test,columns=['predict'])

In [44]:
x_test

word
0     160
1      88
2      81
3     129
4     154
..    ...
195    66
196     0
197   118
198   137
199   142

[200 rows x 1 columns]

In [45]:
y_train

predict
66580       0.0
124787      1.0
95046       1.0
115200      0.0
30912       1.0
...         ...
184968      1.0
38776       0.0
192070      0.0
175698      1.0
171860      1.0

[167392 rows x 1 columns]

In [46]:
pred=model_cnnbilstm.predict(x_test)

In [47]:
pred=pd.DataFrame(data=pred,columns=['predict'])

In [48]:
pred

predict
0        0.0
1        1.0
2        1.0
3        0.0
4        1.0
..       ...
195      1.0
196      0.0
197      0.0
198      1.0
199      0.0

[200 rows x 1 columns]

In [49]:
y_test

predict
0          0
1          0
2          0
3          0
4          0
..       ...
195        0
196        0
197        1
198        0
199        1

[200 rows x 1 columns]

In [50]:
print("XGBoost 보이스 피싱 탐지 테스트 정확도 :", format(accuracy_score(y_test,pred)*100),"%")

XGBoost 보이스 피싱 탐지 테스트 정확도 : 47.5 %
