In [2]:
import pandas as pd 

data=pd.read_csv('/Users/withmocha/Library/CloudStorage/OneDrive-SejongUniversity/3학년 1학기/파이썬기반딥러닝/수업자료/week2/car_evaluation.csv')

data

price  maint  doors persons lug_capacity safety output
0     vhigh  vhigh      2       2        small    low  unacc
1     vhigh  vhigh      2       2        small    med  unacc
2     vhigh  vhigh      2       2        small   high  unacc
3     vhigh  vhigh      2       2          med    low  unacc
4     vhigh  vhigh      2       2          med    med  unacc
...     ...    ...    ...     ...          ...    ...    ...
1723    low    low  5more    more          med    med   good
1724    low    low  5more    more          med   high  vgood
1725    low    low  5more    more          big    low  unacc
1726    low    low  5more    more          big    med   good
1727    low    low  5more    more          big   high  vgood

[1728 rows x 7 columns]

In [3]:
data.isnull().sum()

price           0
maint           0
doors           0
persons         0
lug_capacity    0
safety          0
output          0
dtype: int64

In [5]:
index=data.columns

In [6]:
for i in index:
    print(data[i].dtype)

object
object
object
object
object
object
object


In [7]:
import torch 

torch.tensor([[1.,-1.],[1.,-1.]])



tensor([[ 1., -1.],
        [ 1., -1.]])

In [15]:
print(torch.tensor([[1,2],[3,4]]))
print(torch.tensor([[1,2],[3,4]],device='mps:0')) ## how to use gpu apple silicon mac os  -> CUDA :0 은 윈도우
print(torch.tensor([[1,2],[3,4]],dtype=torch.float64))

tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]], device='mps:0')
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


In [16]:
temp=torch.tensor([[1,2],[3,4]])
print(temp.numpy())

temp=torch.tensor([[1,2],[3,4]],device="mps:0")
print(temp.to("cpu").numpy())

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


In [17]:
temp=torch.FloatTensor([1,2,3,4,5,6,7])
print(temp[0],temp[1],temp[-1])

print('---------------------------')

print(temp[2:5],temp[4:-1])

tensor(1.) tensor(2.) tensor(7.)
---------------------------
tensor([3., 4., 5.]) tensor([5., 6.])


In [18]:
v=torch.tensor([1,2,3])
w=torch.tensor([3,4,6])

print(w-v)

tensor([2, 2, 3])


In [19]:
temp=torch.tensor([[1,2],[3,4]])

print(temp.shape)
print('-------------------')
print(temp.view(4,1))
print('---------------------')
print(temp.view(-1))
print('-------------------')
print(temp.view(1,-1))
print('-----------------------')
print(temp.view(-1,1))

torch.Size([2, 2])
-------------------
tensor([[1],
        [2],
        [3],
        [4]])
---------------------
tensor([1, 2, 3, 4])
-------------------
tensor([[1, 2, 3, 4]])
-----------------------
tensor([[1],
        [2],
        [3],
        [4]])


In [41]:
import pandas as pd 

data=pd.read_csv('/Users/withmocha/Library/CloudStorage/OneDrive-SejongUniversity/3학년 1학기/파이썬기반딥러닝/수업자료/week2/car_evaluation.csv')

data



price  maint  doors persons lug_capacity safety output
0     vhigh  vhigh      2       2        small    low  unacc
1     vhigh  vhigh      2       2        small    med  unacc
2     vhigh  vhigh      2       2        small   high  unacc
3     vhigh  vhigh      2       2          med    low  unacc
4     vhigh  vhigh      2       2          med    med  unacc
...     ...    ...    ...     ...          ...    ...    ...
1723    low    low  5more    more          med    med   good
1724    low    low  5more    more          med   high  vgood
1725    low    low  5more    more          big    low  unacc
1726    low    low  5more    more          big    med   good
1727    low    low  5more    more          big   high  vgood

[1728 rows x 7 columns]

In [8]:
x=torch.from_numpy(data['x'].values).unsqueeze(dim=1).float()
y=torch.from_numpy(data['y'].values).unsqueeze(dim=1).float()

KeyError: 'x'

In [10]:
import pandas as pd 
import torch 
from torch.utils.data import Dataset 
from torch.utils.data import DataLoader 

class CustomDataset(Dataset):
    def __init__(self,csv_file):
        self.label=pd.read_csv(csv_file)
    def __len__(self):
        return len(self.label)
    def __getitem__(self,idx):
        sample=torch.tensor(self.label.iloc[idx,0:3]).int()
        label=torch.tensor(self.label.iloc[idx,3]).int()
        return sample, label

In [ ]:
tensor_dataset=CustomDataset('')
dataset=DataLoader(tensor_dataset, batch_size=4,shuffl=True)