In [9]:
# 도구 임포트
import torch
import torch.nn as nn

In [10]:
# GPU 연산이 가능할 경우 GPU 연산 수행
device ='cuda' if torch.cuda.is_available() else 'cpu'
torch.manual_seed(777)
if device =='cuda':
    torch.cuda.manual_seed_all(777)

In [11]:
# 각 gate 문제에 해당하는 입력과 출력 정의
X = torch.FloatTensor([[0, 0], [0, 1], [1, 0], [1, 1]]).to(device)
Y = torch.FloatTensor([[0], [0], [0], [1]]).to(device) # AND
#Y = torch.FloatTensor([[1], [1], [1], [0]]).to(device) # NAND
#Y = torch.FloatTensor([[0], [1], [1], [1]]).to(device) # OR
#Y = torch.FloatTensor([[0], [1], [1], [0]]).to(device) # XOR

In [12]:
# 다층 퍼셉트론 설계
linear1 = nn.Linear(2, 2, bias=True)
sigmoid1 = nn.Sigmoid()
linear2 = nn.Linear(2, 1, bias=True)
sigmoid2 = nn.Sigmoid()
model = nn.Sequential(linear1, sigmoid1, linear2, sigmoid2).to(
device)
# 이진 분류 문제이므로 비용 함수로 크로스엔트로피 함수 사용
# nn.BCELoss() - 이진 분류에서 사용하는 크로스엔트로피 함수

In [13]:
# 비용 함수와 옵티마이저 정의
criterion = torch.nn.BCELoss().to(device)
optimizer = torch.optim.SGD(model.parameters(), lr=1)

In [14]:
for step in range(1001):
    optimizer.zero_grad()
    hypothesis = model(X)
    
     # 비용 함수
    cost = criterion(hypothesis, Y)
    cost.backward()
    optimizer.step()
    
    if step % 100 == 0: # 100번째 에포크마다 비용 출력
        print(step, cost.item())

0 0.9090930819511414
100 0.2132481038570404
200 0.06191299483180046
300 0.02962685376405716
400 0.018459977582097054
500 0.013130065985023975
600 0.010083194822072983
700 0.00813518837094307
800 0.006792139261960983
900 0.005814610980451107
1000 0.005073647480458021


In [15]:
print('\n\n')
print('hypothesis 값 : ')
print(hypothesis)
print('\n')
predicted = (hypothesis > 0.5).float()
print('예측 값 : ')
print(predicted)
print('\n')
print('실제 값 : ')
print(Y)




hypothesis 값 : 
tensor([[1.3277e-04],
        [3.7380e-03],
        [3.7642e-03],
        [9.8743e-01]], grad_fn=<SigmoidBackward0>)


예측 값 : 
tensor([[0.],
        [0.],
        [0.],
        [1.]])


실제 값 : 
tensor([[0.],
        [0.],
        [0.],
        [1.]])
