In [1]:
import torch
import torch.nn as nn


In [2]:
# GPU 연산이 가능할 경우 GPU 연산 수행
device ='cuda' if torch.cuda.is_available() else 'cpu'
torch.manual_seed(777)
if device =='cuda':
    torch.cuda.manual_seed_all(777)

In [3]:
# 각 gate 문제에 해당하는 입력과 출력 정의
X = torch.FloatTensor([[0, 0], [0, 1], [1, 0], [1, 1]]).to(device)
Y = torch.FloatTensor([[0], [0], [0], [1]]).to(device) # AND
#Y = torch.FloatTensor([[1], [1], [1], [0]]).to(device) # NAND
#Y = torch.FloatTensor([[0], [1], [1], [1]]).to(device) # OR
#Y = torch.FloatTensor([[0], [1], [1], [0]]).to(device) # XOR

In [4]:
# 단층 퍼셉트론 설계
linear = nn.Linear(2, 1, bias=True)
sigmoid = nn.Sigmoid()
model = nn.Sequential(linear, sigmoid).to(device)
# 이진 분류 문제이므로 비용 함수로 크로스엔트로피 함수 사용
# nn.BCELoss() - 이진 분류에서 사용하는 크로스엔트로피 함수

In [5]:
# 비용 함수와 옵티마이저 정의
criterion = torch.nn.BCELoss().to(device)
optimizer = torch.optim.SGD(model.parameters(), lr=1)

In [6]:
for step in range(1001):
    optimizer.zero_grad()
    hypothesis = model(X)
    # 비용 함수
    cost = criterion(hypothesis, Y)
    cost.backward()
    optimizer.step()
    if step % 100 == 0: # 100번째 에포크마다 비용 출력
        print(step, cost.item())

0 0.6932064294815063
100 0.14414836466312408
200 0.0817771703004837
300 0.05658476799726486
400 0.04307378828525543
500 0.03469350188970566
600 0.029005466029047966
700 0.024899723008275032
800 0.021800503134727478
900 0.01938023790717125
1000 0.01743890717625618


In [7]:
print('\n\n')
print('hypothesis 값 : ')
print(hypothesis)
print('\n')
predicted = (hypothesis > 0.5).float()
print('예측 값 : ')
print(predicted)
print('\n')
print('실제 값 : ')
print(Y)




hypothesis 값 : 
tensor([[1.2500e-05],
        [2.0266e-02],
        [2.0266e-02],
        [9.7162e-01]], grad_fn=<SigmoidBackward0>)


예측 값 : 
tensor([[0.],
        [0.],
        [0.],
        [1.]])


실제 값 : 
tensor([[0.],
        [0.],
        [0.],
        [1.]])
