In [1]:
import torch
import torch.nn as nn 
import torch.optim as optim
import numpy as np
from torch.utils.data import random_split
from xgboost.sklearn import XGBClassifier


In [13]:
def load_data(filename):
    data = np.loadtxt(filename, delimiter=',', dtype=np.float32)
    x = data[:, 0:-2]
    y = data[:, [-1]] # after 3 months (-2) and 6 months (-1)
    return torch.tensor(x, dtype=torch.float32), torch.tensor(y, dtype=torch.float32)

In [14]:
# target to fix code


class FNN(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(FNN, self).__init__()
        self.layer1 = nn.Sequential(nn.Linear(input_size, hidden_size), nn.Sigmoid())
        self.layer2 = nn.Sequential(nn.Linear(hidden_size, output_size), nn.Sigmoid())
        #self.dropout = nn.Dropout(0.25)
        #self.dropout = nn.Dropout(0.5)
        #self.layer1 = nn.Sequential(nn.Linear(input_size, hidden_size), nn.Tanh())
        self.activation = torch.nn.ReLU()
        #self.dropout = nn.Dropout(0.1)
        #self.layer2 = nn.Sequential(nn.Linear(hidden_size, output_size), nn.Sigmoid())
        #self.dropout = nn.Dropout(0.1)
        #self.activation = torch.nn.ReLU()
        
        
        

        
    def forward(self, x):
        x = self.layer1(x)
        x = self.layer2(x)
        x = self.activation(x)
        
        
        return x # return model

In [15]:
x_train, y_train = load_data('/Users/withmocha/Library/CloudStorage/OneDrive-SejongUniversity/3학년 2학기/딥러닝개론/과제/과제1/hw1_training_dataset.csv')
x_test, y_test = load_data('/Users/withmocha/Library/CloudStorage/OneDrive-SejongUniversity/3학년 2학기/딥러닝개론/과제/과제1/hw1_test_dataset.csv')

In [16]:
y_train

tensor([[1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
      

In [17]:
x_test

tensor([[0.2474, 0.5331, 0.1690, 0.5000, 0.7500, 0.4545, 0.9561, 0.2500, 0.3926,
         0.2303, 0.2000, 0.0556, 0.0000, 0.3043, 0.0500],
        [0.2474, 0.5331, 0.1690, 0.5000, 0.7500, 0.4545, 0.9561, 0.2500, 0.3926,
         0.2303, 0.3000, 0.0556, 0.0000, 0.3043, 0.0500],
        [0.3268, 0.3718, 0.3380, 0.5000, 0.5000, 0.5455, 0.5575, 0.2500, 0.3998,
         0.2061, 0.7000, 0.6111, 1.0000, 0.1652, 0.4800],
        [0.0042, 0.4179, 0.2535, 0.5000, 0.2500, 0.2727, 0.3986, 0.0000, 0.0000,
         0.2388, 0.6000, 0.5000, 1.0000, 0.1739, 0.7500],
        [0.3268, 0.3718, 0.3380, 0.5000, 0.5000, 0.5455, 0.5575, 0.2500, 0.3998,
         0.2061, 1.0000, 0.7222, 0.0000, 0.1739, 0.0000],
        [0.3208, 0.4467, 0.2676, 0.5000, 0.7500, 0.2727, 0.7489, 0.2812, 0.3559,
         0.1939, 1.0000, 0.7222, 0.0000, 0.3043, 0.7500],
        [0.0084, 0.5389, 0.0000, 1.0000, 0.2500, 0.1818, 0.6514, 0.0000, 0.0735,
         0.3152, 0.4000, 1.0000, 1.0000, 0.2609, 0.0000],
        [0.0168, 0.7176, 0.

In [18]:
x_train.shape

torch.Size([103, 15])

In [19]:


from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test) # test set에는 transform만 사용하기


x_train=torch.Tensor(x_train)
x_test=torch.Tensor(x_test)

In [20]:
model = FNN(input_size=15, hidden_size=300, output_size=1)
criterion = nn.BCELoss()
#optimizer = optim.Adam(model.parameters(),lr=0.05, betas=(0.95, 0.999),eps=1e-08,weight_decay=0.0001) # target to fix
optimizer = optim.Adam(model.parameters(),lr=0.05, betas=(0.95, 0.999),eps=1e-08,weight_decay=0.0001) # target to fix

In [21]:
for param in model.parameters():
    print(param)

Parameter containing:
tensor([[ 0.2247,  0.0026,  0.1028,  ..., -0.1971, -0.1858,  0.0347],
        [-0.2566,  0.2217, -0.1895,  ..., -0.0910,  0.2398, -0.2491],
        [ 0.2314,  0.0113,  0.0963,  ...,  0.2104, -0.2335, -0.2024],
        ...,
        [-0.0418,  0.0075,  0.1211,  ...,  0.0920,  0.2563,  0.0965],
        [-0.2381, -0.1020,  0.0381,  ...,  0.1768, -0.0333,  0.0783],
        [ 0.1427, -0.0880,  0.1558,  ..., -0.0447,  0.1560,  0.0564]],
       requires_grad=True)
Parameter containing:
tensor([ 6.7437e-02, -7.0014e-02,  1.0094e-01, -3.1318e-02, -2.4819e-02,
         8.3082e-02, -6.0156e-02, -9.4555e-03, -1.2975e-01, -1.3270e-03,
         6.0306e-02,  2.5789e-01,  1.9960e-01,  3.1466e-02,  5.8839e-03,
         5.8269e-02,  2.5629e-01, -1.9571e-01, -8.2677e-02, -1.6915e-01,
         1.1714e-01,  2.1802e-01, -1.8903e-01,  8.6899e-02,  1.1661e-01,
        -4.1998e-02,  1.9497e-01,  1.4494e-02, -2.4810e-01, -2.8084e-02,
        -1.8231e-01,  2.1936e-01,  1.3130e-01,  3.8777e-0

In [22]:
# assuming y is torch.Tensor

In [23]:
num_epochs = 1001

for epoch in range(num_epochs):
    outputs = model(x_train)
    loss = criterion(outputs, y_train)
    
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    
    if epoch % 200 == 0:
        print(f'Epoch [{epoch}/{num_epochs}], Loss: {loss.item():.4f}')
        

with torch.no_grad(): 
    train_accuracy = (model(x_train).gt(0.5).float() == y_train).float().mean().item()
    test_accuracy = (model(x_test).gt(0.5).float() == y_test).float().mean().item()
    
    

print(f'\nTrain Accuracy: {train_accuracy:.4f}')
print(f'Test Accuracy: {test_accuracy:.4f}')
#Train Accuracy: 0.9709 -> start
#Test Accuracy: 0.9000 -> start

Epoch [0/1001], Loss: 0.6917
Epoch [200/1001], Loss: 0.1252
Epoch [400/1001], Loss: 0.0460
Epoch [600/1001], Loss: 0.0288
Epoch [800/1001], Loss: 0.0219
Epoch [1000/1001], Loss: 0.0181

Train Accuracy: 1.0000
Test Accuracy: 0.9500
