In [2]:
import pandas as pd   
import math
import time
import librosa
import whisper
from pydub import AudioSegment
import numpy as np 
import torch
import torch.nn as nn

In [4]:

model = whisper.load_model("small")


audio_path = "/Users/withmocha/Downloads/대출빙자 5단계(금전 편취 시도)_.mp3"


result = model.transcribe(audio_path)


print(result["text"])

/opt/anaconda3/envs/conda_cpu/lib/python3.12/site-packages/whisper/transcribe.py:115: UserWarning: FP16 is not supported on CPU; using FP32 instead
  warnings.warn("FP16 is not supported on CPU; using FP32 instead")


 심사과에서 말씀하시는 조건이라는 게 지금 고객님께서 보여주신 채무 1포를 고객님께서 직접 상한체되어 하셔서 채무 공감만 조금 만들어 주시며 금액권은 동일하게 조건 부승인권으로 당일 종으로도 수령 가능하다고 말씀하시거든요. 호견아 오해하실까봐 말씀드리는 건데 저희 쪽으로 나빠지는 거 절대로 아니세요. 좀 연락하셔가지고 고객님 채무 상한체로 하시는 거고요. 지금 심사과에서 말씀하시는 금액 최소변제 금액 300만 원이세요. 물론 300만 원은 조금 금액이 아니잖아요. 고객님 2400만 원 나가시잖아요. 대환하실 게 2300이시고 생계제금 100만 원이신데 300만 원 상한하시면 대환하실 금액이 줄어드시는 거잖아요. 단어로. 그러면 생계제금이 400만 원 된다고 생각하시면 되시는 거거든요. 나문자금은 고객님 다른 종수로 사용하셔도 뭐가 하신 거기 때문에 당일종으로 고객님한테 들어가신다고 생각하시면 되시는 거거든요. 좀 힘드시겠지만 고객님께서 채무 엿들부, 엿들부, 엿들부, 어느 쪽으로든 300만 원 정도 채무 직접 상한 처리가 가능하실까요.


In [224]:
start = time.time()

result["text"]

' 심사과에서 말씀하시는 조건이라는 게 지금 고객님께서 보여주신 채무 1포를 고객님께서 직접 상한체되어 하셔서 채무 공감만 조금 만들어 주시며 금액권은 동일하게 조건 부승인권으로 당일 종으로도 수령 가능하다고 말씀하시거든요. 호견아 오해하실까봐 말씀드리는 건데 저희 쪽으로 나빠지는 거 절대로 아니세요. 좀 연락하셔가지고 고객님 채무 상한체로 하시는 거고요. 지금 심사과에서 말씀하시는 금액 최소변제 금액 300만 원이세요. 물론 300만 원은 조금 금액이 아니잖아요. 고객님 2400만 원 나가시잖아요. 대환하실 게 2300이시고 생계제금 100만 원이신데 300만 원 상한하시면 대환하실 금액이 줄어드시는 거잖아요. 단어로. 그러면 생계제금이 400만 원 된다고 생각하시면 되시는 거거든요. 나문자금은 고객님 다른 종수로 사용하셔도 뭐가 하신 거기 때문에 당일종으로 고객님한테 들어가신다고 생각하시면 되시는 거거든요. 좀 힘드시겠지만 고객님께서 채무 엿들부, 엿들부, 엿들부, 어느 쪽으로든 300만 원 정도 채무 직접 상한 처리가 가능하실까요.'

In [225]:
A=len(result["text"])

In [226]:
A

530

In [227]:
B=len("1단계로 알겠고요. 저희는 KB 금융괴로서 KB 저축은행인데요. 지금 5월에 저희는 대한대출 플러스 생활료지사금적으로 나온 대출 상품이 있어요. 그리고 연휴율이 7.8%대로 진행하는 부분이고 상원 기간이 온앤까지고요")

In [228]:

audio = AudioSegment.from_mp3(audio_path)

print(f"Channels: {audio.channels}")
print(f"Sample Width: {audio.sample_width}")
print(f"Frame Rate (Sample Rate): {audio.frame_rate}")
print(f"Frame Width: {audio.frame_width}")
print(f"Length (ms): {len(audio)}")

Channels: 2
Sample Width: 2
Frame Rate (Sample Rate): 44100
Frame Width: 4
Length (ms): 56216


huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)


In [229]:
seconds=(len(audio)/1000.0)%60

In [230]:
seconds

56.216

In [231]:
target_time=seconds/A

In [232]:
target_time#1문자 시간

0.10606792452830188

In [233]:
cost_time=target_time*220# 숫자는 문자의 갯수

In [234]:
cost_time

23.334943396226414

In [235]:
seconds=(target_time/1000)%60
print(seconds)

0.00010606792452830188


In [236]:
target_data=pd.DataFrame(index=range(1),columns=['sentence'])

In [237]:
target_data.iloc[0,0]=result['text'][:220]

In [238]:
target_data

sentence
0   심사과에서 말씀하시는 조건이라는 게 지금 고객님께서 보여주신 채무 1포를 고객님께...

In [239]:
target_data.to_csv("data.csv")

In [240]:
count_s = 0
B = []
original_str = target_data.iloc[0,0]
A = len(original_str)

for j in range(A):
    char = original_str[j]
    if char not in [',', '\'', '[', ']']:
        B.append(char)
    if char == '.':
        count_s += 1
    if count_s == 4:
        break 
    if len(B)>200:
        break    

new_str = ''.join(B)
target_data.iloc[0,0] = new_str

In [241]:
target_data.iloc[0,0]

' 심사과에서 말씀하시는 조건이라는 게 지금 고객님께서 보여주신 채무 1포를 고객님께서 직접 상한체되어 하셔서 채무 공감만 조금 만들어 주시며 금액권은 동일하게 조건 부승인권으로 당일 종으로도 수령 가능하다고 말씀하시거든요. 호견아 오해하실까봐 말씀드리는 건데 저희 쪽으로 나빠지는 거 절대로 아니세요. 좀 연락하셔가지고 고객님 채무 상한체로 하시는 거고요. 지'

In [242]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer('sentence-transformers/all-mpnet-base-v2')

In [243]:
A=model.encode(target_data.iloc[0,0])

In [244]:
list=[]

for i in range(A.shape[0]):
    list.append(i)

In [245]:
x_train=pd.DataFrame(index=range(1),columns=list)

In [246]:
x_train

0    1    2    3    4    5    6    7    8    9    ...  758  759  760  761  \
0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN   

   762  763  764  765  766  767  
0  NaN  NaN  NaN  NaN  NaN  NaN  

[1 rows x 768 columns]

In [247]:
vector=[]
vector=model.encode(target_data.iloc[0,0])  
for j in range(x_train.shape[1]):
        x_train.iloc[0,j]=vector[j]  
    

In [248]:
x_train

0        1         2         3         4         5         6    \
0  0.062527 -0.03124 -0.029226 -0.031507 -0.005363  0.004466  0.021148   

        7         8         9    ...       758      759       760       761  \
0 -0.009256  0.048196 -0.007161  ... -0.018421 -0.03065 -0.050301  0.018183   

        762       763       764       765       766       767  
0 -0.032043 -0.064806  0.039445  0.033233  0.012094 -0.044937  

[1 rows x 768 columns]

In [249]:
X_train = torch.tensor(x_train.iloc[0], dtype=torch.float).unsqueeze(1)

In [250]:
X_train = X_train.reshape(1, 1, 768)

In [251]:
X_train

tensor([[[ 6.2527e-02, -3.1240e-02, -2.9226e-02, -3.1507e-02, -5.3628e-03,
           4.4662e-03,  2.1148e-02, -9.2561e-03,  4.8196e-02, -7.1606e-03,
          -4.9927e-03,  2.2249e-02,  1.9247e-02, -5.6684e-02, -2.1846e-02,
          -2.4885e-02,  2.8046e-02,  5.2424e-02,  5.1724e-02,  6.0366e-03,
          -3.1956e-02,  2.1701e-02,  1.2596e-02,  2.5772e-02,  2.5133e-02,
          -1.2902e-02,  7.0017e-03,  1.3715e-02,  1.2958e-02, -9.6622e-02,
          -1.1647e-02,  3.1405e-02, -2.1287e-02, -2.6298e-02,  3.0599e-06,
          -4.0088e-02,  2.8714e-02,  1.1348e-02,  6.1243e-03, -1.0215e-03,
           3.6927e-02, -2.9489e-03, -1.3880e-02, -8.0824e-03,  2.8366e-02,
          -4.1638e-02,  1.8718e-02,  6.3849e-05,  4.3699e-02,  9.3564e-03,
          -2.5409e-02, -5.7358e-03, -9.9859e-02, -7.5454e-04,  6.8451e-03,
           2.2811e-02,  1.1191e-02, -2.5959e-02, -4.3818e-02, -7.9176e-03,
          -2.6306e-02,  1.7987e-02, -1.2164e-02,  1.8984e-02, -1.1842e-02,
           1.7760e-02,  2

In [252]:
class MyModel(nn.Module):
    def __init__(self):
        super(MyModel, self).__init__()
        self.conv1 = nn.Conv1d(in_channels=X_train.shape[2], out_channels=128, kernel_size=1)
        self.bn1 = nn.BatchNorm1d(128)  
        self.conv2 = nn.Conv1d(in_channels=128, out_channels=64, kernel_size=1)
        self.bn2 = nn.BatchNorm1d(64)  
        self.conv3 = nn.Conv1d(in_channels=64, out_channels=32, kernel_size=1)
        self.bn3 = nn.BatchNorm1d(32)  
        self.pool = nn.MaxPool1d(kernel_size=1)
        self.dropout = nn.Dropout(0.5)
        self.lstm = nn.LSTM(input_size=32, hidden_size=128, num_layers=2, batch_first=True, bidirectional=True)
        self.fc1 = nn.Linear(128*2, 32)
        self.fc2 = nn.Linear(32, 3)
        self.activation = nn.ELU()

    def forward(self, x):
        x = x.permute(0, 2, 1)
        x = self.activation(self.bn1(self.conv1(x)))
        x = self.activation(self.bn2(self.conv2(x)))
        x = self.activation(self.bn3(self.conv3(x)))
        x = self.pool(x)
        x = self.dropout(x)
        x = x.permute(0, 2, 1)
        x, _ = self.lstm(x)
        x = self.dropout(x[:, -1, :])
        x = self.activation(self.fc1(x))
        x = self.dropout(x)
        x = self.fc2(x)
        return x

In [253]:
model = MyModel()

In [254]:
state_dict = torch.load("/Users/withmocha/Desktop/DATA/Capston Design(2024)/data(sentence)/0518(final)/model/Voice fishing Detection Model.pt")
model.load_state_dict(state_dict)

<All keys matched successfully>

In [255]:
model.eval()

MyModel(
  (conv1): Conv1d(768, 128, kernel_size=(1,), stride=(1,))
  (bn1): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (conv2): Conv1d(128, 64, kernel_size=(1,), stride=(1,))
  (bn2): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (conv3): Conv1d(64, 32, kernel_size=(1,), stride=(1,))
  (bn3): BatchNorm1d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (pool): MaxPool1d(kernel_size=1, stride=1, padding=0, dilation=1, ceil_mode=False)
  (dropout): Dropout(p=0.5, inplace=False)
  (lstm): LSTM(32, 128, num_layers=2, batch_first=True, bidirectional=True)
  (fc1): Linear(in_features=256, out_features=32, bias=True)
  (fc2): Linear(in_features=32, out_features=3, bias=True)
  (activation): ELU(alpha=1.0)
)

In [256]:
y_score = model(X_train).detach().numpy()

In [257]:
y_score

array([[-9.600656 ,  1.9379278,  1.9807259]], dtype=float32)

In [258]:
y_pred = np.argmax(y_score, axis=1)

In [259]:
y_pred

array([2])

In [260]:
print(f"{time.time()-start:.4f} sec")

3.0727 sec
