In [54]:
import pandas as pd

data_row=pd.read_csv("/Users/withmocha/Desktop/DATA/Capston Design(2024)/Data(24.03.12)/data(use)/model train(already concat)/shuffle_data_sum.csv")

data_row

Unnamed: 0  word     predict
0           116342     년  No fishing
1            92425    유료  No fishing
2           119617    단순     fishing
3            80725    접수  No fishing
4            38425  홈페이지  No fishing
...            ...   ...         ...
209236       65678    금융     fishing
209237      149035     것  No fishing
209238      144267    누출     fishing
209239       99456   수사관     fishing
209240      174608    하나     fishing

[209241 rows x 3 columns]

In [55]:
data_row.isnull().sum()

Unnamed: 0    0
word          0
predict       0
dtype: int64

In [56]:
data_row.drop(columns=["Unnamed: 0"],inplace=True)

In [57]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [58]:
print(data_row.iloc[1,0]==data_row.iloc[2,0])

False


In [59]:
A=le.fit_transform(data_row['word'])

In [60]:
A.dtype

dtype('int64')

In [61]:
for i in range(data_row.shape[0]):
    data_row.iloc[i,0]=A[i]

In [62]:
data=data_row

In [63]:
A=le.fit_transform(data['predict'])

In [64]:
data

word     predict
0       1185  No fishing
1       4384  No fishing
2       1324     fishing
3       5159  No fishing
4       6804  No fishing
...      ...         ...
209236   864     fishing
209237   278  No fishing
209238  1267     fishing
209239  3306     fishing
209240  6519     fishing

[209241 rows x 2 columns]

In [65]:
A

array([0, 0, 1, ..., 1, 1, 1])

In [66]:
for i in range(data.shape[0]):
    data.iloc[i,1]=A[i]

In [67]:
data.columns

Index(['word', 'predict'], dtype='object')

In [68]:
data

word predict
0       1185       0
1       4384       0
2       1324       1
3       5159       0
4       6804       0
...      ...     ...
209236   864       1
209237   278       0
209238  1267       1
209239  3306       1
209240  6519       1

[209241 rows x 2 columns]

In [69]:
data.astype('int32').dtypes

word       int32
predict    int32
dtype: object

In [70]:
x_train=pd.DataFrame(data=data['word'],columns=['word'])

In [71]:
x_train

word
0       1185
1       4384
2       1324
3       5159
4       6804
...      ...
209236   864
209237   278
209238  1267
209239  3306
209240  6519

[209241 rows x 1 columns]

In [72]:

y_train=pd.DataFrame(data=data['predict'],columns=['predict'],copy=True)

In [73]:

y_train

predict
0            0
1            0
2            1
3            0
4            0
...        ...
209236       1
209237       0
209238       1
209239       1
209240       1

[209241 rows x 1 columns]

In [74]:

x_train.astype('int32').dtypes
y_train.astype('int32').dtypes


predict    int32
dtype: object

In [75]:
data=x_train

In [76]:
target=y_train

In [77]:
import numpy as np
from sklearn.model_selection import train_test_split

In [78]:
x_train['word']=x_train['word'].astype(float)
y_train['predict']=y_train['predict'].astype(float)

In [79]:
x_train,x_valid,y_train,y_valid=train_test_split(data,target,test_size=0.4,shuffle=True,stratify=target)

In [80]:
print(x_train.dtypes)
print(y_train.dtypes)
print(x_valid.dtypes)

word    float64
dtype: object
predict    float64
dtype: object
word    float64
dtype: object


In [106]:

from xgboost import XGBClassifier

# 모델 선언 예시
model = XGBClassifier(objective='binary:logistic',eval_metric='rmse')
model.fit(x_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='rmse', feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, random_state=None, ...)

In [107]:
y_pred=model.predict(x_valid)

In [108]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score

In [109]:
print("XGBoost 보이스 피싱 탐지 정확도 : ", format(accuracy_score(y_valid,y_pred)*100))

XGBoost 보이스 피싱 탐지 정확도 :  71.71583210867773


In [110]:
print(f1_score(y_valid, y_pred, zero_division=1.0))

0.6964805436245913


In [86]:
test_data=pd.read_csv("/Users/withmocha/Desktop/DATA/Capston Design(2024)/Data(24.03.12)/data(use)/model train(already concat)/test_smalldata.csv")

In [87]:
test_data

Unnamed: 0 word     predict
0             0   회수  No fishing
1             1  시스템  No fishing
2             2  서울시  No fishing
3             3  지방세  No fishing
4             4   한계  No fishing
..          ...  ...         ...
195         195   부심  No fishing
196         196   가능  No fishing
197         197   정도     fishing
198         198   출력  No fishing
199         199   카드     fishing

[200 rows x 3 columns]

In [88]:
test_data.drop(columns=['Unnamed: 0'],inplace=True)

In [89]:
x_test=pd.DataFrame(data=test_data['word'],columns=['word'])

In [90]:
x_test

word
0     회수
1    시스템
2    서울시
3    지방세
4     한계
..   ...
195   부심
196   가능
197   정도
198   출력
199   카드

[200 rows x 1 columns]

In [91]:
y_test=pd.DataFrame(data=test_data['predict'],columns=['predict'])

In [92]:
y_test

predict
0    No fishing
1    No fishing
2    No fishing
3    No fishing
4    No fishing
..          ...
195  No fishing
196  No fishing
197     fishing
198  No fishing
199     fishing

[200 rows x 1 columns]

In [93]:
#le = LabelEncoder()

In [94]:
x_test=le.fit_transform(x_test['word'])
y_test=le.fit_transform(y_test['predict'])

In [95]:
x_test

array([160,  88,  81, 129, 154, 116,  51, 157,  61,   2,  39, 133, 151,
        70,  27,  40, 122,  48, 153,  47, 113,  35,  23,  86,  11,  85,
        49,   6, 134,  80,  54,  75,  28,  62,  71,  94, 104,   8,  95,
        82, 152, 107,  23, 106,  85, 146, 162,  79, 116,   0,  65,   6,
       129, 144, 139,  70,   0,  60,  57,  89,   4, 112,  16, 145,  52,
         6,  50,  93, 117,   6,  21,  67,  32,  15, 119,  98, 111, 119,
        96,   7,  76,  22,  91, 110,  29,  26,  30, 135, 108,  20,  78,
       115,  56,   6, 132,  64,  68, 116, 152,   8, 125,  97,  69,  36,
        33, 143, 127,  74,  83,  87,  70, 131,  80,   6,  58, 116, 159,
       120, 101,  18, 147, 153,  25, 131, 126,  59,  34, 141, 102,  41,
        43,   6,   0,  99, 108,  63, 128,  46,  72,  42,   3, 100, 105,
         1,  55,   5,  53,  84,  94, 116, 152,  90,  72, 124, 136,  12,
        63, 114,  24,  21, 150,  44, 130,   9,  94,  85,  65,  14, 115,
        77,  10,  37,  52,  73, 155,  31, 140, 158, 109, 156, 16

In [96]:
y_test

array([0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1])

In [97]:
x_test=pd.DataFrame(data=x_test,columns=['word'])
y_test=pd.DataFrame(data=y_test,columns=['predict'])

In [98]:
x_test

word
0     160
1      88
2      81
3     129
4     154
..    ...
195    66
196     0
197   118
198   137
199   142

[200 rows x 1 columns]

In [99]:
y_train

predict
58591       1.0
75054       0.0
192520      0.0
37595       0.0
163024      0.0
...         ...
174085      0.0
203922      0.0
108949      0.0
142818      0.0
92909       1.0

[125544 rows x 1 columns]

In [100]:
pred=model.predict(x_test)

In [101]:
pred=pd.DataFrame(data=pred,columns=['predict'])

In [102]:
pred

predict
0          1
1          0
2          1
3          0
4          1
..       ...
195        1
196        0
197        0
198        0
199        0

[200 rows x 1 columns]

In [103]:
y_test

predict
0          0
1          0
2          0
3          0
4          0
..       ...
195        0
196        0
197        1
198        0
199        1

[200 rows x 1 columns]

In [104]:
print("XGBoost 보이스 피싱 탐지 테스트 정확도 : ", format(accuracy_score(y_test,pred)*100))

XGBoost 보이스 피싱 탐지 테스트 정확도 :  54.0


In [105]:
print(f1_score(y_test, pred, zero_division=1.0))

0.3235294117647059
