In [122]:
import pandas as pd

data_row=pd.read_csv("/Users/withmocha/Desktop/DATA/Capston Design(2024)/Data(24.03.12)/data(use)/frequency base/data_frequency_final.csv")

data_row

Unnamed: 0  word     predict
0                0     년  No fishing
1                1    단순     fishing
2                2    접수  No fishing
3                3  홈페이지  No fishing
4                4     거     fishing
...            ...   ...         ...
149359      149359    거주  No fishing
149360      149360    백만     fishing
149361      149361    금융     fishing
149362      149362     것  No fishing
149363      149363    하나     fishing

[149364 rows x 3 columns]

In [123]:
data_row.isnull().sum()

Unnamed: 0    0
word          0
predict       0
dtype: int64

In [124]:
data_row.drop(columns=["Unnamed: 0"],inplace=True)

In [125]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [126]:
print(data_row.iloc[1,0]==data_row.iloc[2,0])

False


In [127]:
A=le.fit_transform(data_row['word'])

In [128]:
A.dtype

dtype('int64')

In [129]:
for i in range(data_row.shape[0]):
    data_row.iloc[i,0]=A[i]

In [130]:
data=data_row

In [131]:
A=le.fit_transform(data['predict'])

In [132]:
data

word     predict
0       174  No fishing
1       187     fishing
2       666  No fishing
3       864  No fishing
4        33     fishing
...     ...         ...
149359   36  No fishing
149360  305     fishing
149361  137     fishing
149362   52  No fishing
149363  838     fishing

[149364 rows x 2 columns]

In [133]:
A

array([0, 1, 0, ..., 1, 0, 1])

In [134]:
for i in range(data.shape[0]):
    data.iloc[i,1]=A[i]

In [135]:
data.columns

Index(['word', 'predict'], dtype='object')

In [136]:
data

word predict
0       174       0
1       187       1
2       666       0
3       864       0
4        33       1
...     ...     ...
149359   36       0
149360  305       1
149361  137       1
149362   52       0
149363  838       1

[149364 rows x 2 columns]

In [137]:
#from sklearn.preprocessing import StandardScaler

#scaler=StandardScaler()
#data=pd.DataFrame(scaler.fit_transform(data),columns=['word','predict'])

In [138]:
data.astype('int32').dtypes

word       int32
predict    int32
dtype: object

In [139]:
x_train=pd.DataFrame(data=data['word'],columns=['word'])

In [140]:
x_train

word
0       174
1       187
2       666
3       864
4        33
...     ...
149359   36
149360  305
149361  137
149362   52
149363  838

[149364 rows x 1 columns]

In [141]:

y_train=pd.DataFrame(data=data['predict'],columns=['predict'],copy=True)

In [142]:

y_train

predict
0            0
1            1
2            0
3            0
4            1
...        ...
149359       0
149360       1
149361       1
149362       0
149363       1

[149364 rows x 1 columns]

In [143]:

x_train.astype('int32').dtypes
y_train.astype('int32').dtypes


predict    int32
dtype: object

In [144]:
data=x_train

In [145]:
target=y_train

In [146]:
import numpy as np
from sklearn.model_selection import train_test_split

In [147]:
x_train['word']=x_train['word'].astype(float)
y_train['predict']=y_train['predict'].astype(float)

In [148]:
x_train,x_valid,y_train,y_valid=train_test_split(data,target,test_size=0.2,shuffle=True,stratify=target)

In [149]:
print(x_train.dtypes)
print(y_train.dtypes)
print(x_valid.dtypes)

word    float64
dtype: object
predict    float64
dtype: object
word    float64
dtype: object


In [150]:

from xgboost import XGBClassifier

# 모델 선언 예시
model = XGBClassifier(eta=0.1,max_depth=2,n_estimators=10,min_child_weight=0.5,gamma=10)
model.fit(x_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eta=0.1, eval_metric=None,
              feature_types=None, gamma=10, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=2,
              max_leaves=None, min_child_weight=0.5, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=10,
              n_jobs=None, num_parallel_tree=None, ...)

In [151]:
y_pred=pd.DataFrame(model.predict(x_valid),columns=['predict'])

In [152]:
y_valid

predict
145694      1.0
108661      1.0
26195       1.0
22350       1.0
142791      0.0
...         ...
11747       1.0
72859       0.0
37207       0.0
4768        0.0
39306       1.0

[29873 rows x 1 columns]

In [153]:
y_pred

predict
0            0
1            0
2            0
3            0
4            0
...        ...
29868        0
29869        0
29870        0
29871        0
29872        0

[29873 rows x 1 columns]

In [156]:
from sklearn.metrics import accuracy_score

print(accuracy_score(y_valid,y_pred)*100)

60.64673785692766


In [157]:
test_data=pd.read_csv("/Users/withmocha/Desktop/DATA/Capston Design(2024)/Data(24.03.12)/data(use)/data(small)/test/test_data_small.csv")

In [158]:
test_data

Unnamed: 0 word     predict
0             0   상시  NO fishing
1             1   우편  NO fishing
2             2   요금  NO fishing
3             3   근거     fishing
4             4   구분  NO fishing
..          ...  ...         ...
195         195   세탁     fishing
196         196   실업  NO fishing
197         197   맹점  NO fishing
198         198   걸로  NO fishing
199         199    십     fishing

[200 rows x 3 columns]

In [159]:
test_data.drop(columns=['Unnamed: 0'],inplace=True)

In [160]:
x_test=pd.DataFrame(data=test_data['word'],columns=['word'])

In [161]:
x_test

word
0     상시
1     우편
2     요금
3     근거
4     구분
..   ...
195   세탁
196   실업
197   맹점
198   걸로
199    십

[200 rows x 1 columns]

In [162]:
y_test=pd.DataFrame(data=test_data['predict'],columns=['predict'])

In [163]:
y_test

predict
0    NO fishing
1    NO fishing
2    NO fishing
3       fishing
4    NO fishing
..          ...
195     fishing
196  NO fishing
197  NO fishing
198  NO fishing
199     fishing

[200 rows x 1 columns]

In [164]:
#le = LabelEncoder()

In [165]:
x_test=le.fit_transform(x_test['word'])
y_test=le.fit_transform(y_test['predict'])

In [166]:
x_test

array([ 90, 115, 114,  32,  24,  13,  10, 109, 173, 184,  38,  25,  47,
       121,  27,  41,  36, 162,  39,  44,  18,  26,  82,  77,  85, 125,
       171, 116, 148, 157,  37,  60, 179,  22,  28,  57, 146, 118,  59,
        75, 131, 130,  78, 170,  94,  78,  86,  68,  87,  63, 121,  72,
       163,  76, 181, 129, 169,   0, 178, 124,  95, 182,  89,  91, 184,
        97, 102,  30,   7, 172, 152,   5,  64,  34, 180,  12, 117,   4,
       119,  54,  52,  79, 101, 174, 110, 133, 159,  42, 164,   2, 134,
         1,  67, 157,  46,  19,   9, 166, 104,  45,   6, 155, 168,  23,
        11, 135,  43, 154,  93,  47,  48, 140,  14, 145, 137, 147,  20,
       161,  70, 143,  69,   8,  38, 132,  97, 177,   6, 113, 120,  74,
       111,  65, 144,  99, 150, 103, 142,  73,  15,  49,  58,  51,  40,
       139, 136,  96, 151, 167, 149, 183, 122, 127, 185,  35, 138,  55,
         5, 107, 112, 153, 123, 141,  71,  33,  98,  80,  58,  16,  53,
        50,  81,  29, 108, 108,  88,  84,  61,  21, 165, 160, 10

In [167]:
y_test

array([0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1])

In [168]:
x_test=pd.DataFrame(data=x_test,columns=['word'])
y_test=pd.DataFrame(data=y_test,columns=['predict'])

In [169]:
x_test

word
0      90
1     115
2     114
3      32
4      24
..    ...
195    92
196   105
197    56
198    17
199   106

[200 rows x 1 columns]

In [170]:
y_test

predict
0          0
1          0
2          0
3          1
4          0
..       ...
195        1
196        0
197        0
198        0
199        1

[200 rows x 1 columns]

In [171]:
x_test

word
0      90
1     115
2     114
3      32
4      24
..    ...
195    92
196   105
197    56
198    17
199   106

[200 rows x 1 columns]

In [172]:
y_test

predict
0          0
1          0
2          0
3          1
4          0
..       ...
195        1
196        0
197        0
198        0
199        1

[200 rows x 1 columns]

In [173]:
pred=model.predict(x_test)

In [174]:
pred=pd.DataFrame(data=pred,columns=['predict'])

In [175]:
pred

predict
0          0
1          0
2          0
3          1
4          1
..       ...
195        0
196        0
197        0
198        0
199        0

[200 rows x 1 columns]

In [176]:
y_test

predict
0          0
1          0
2          0
3          1
4          0
..       ...
195        1
196        0
197        0
198        0
199        1

[200 rows x 1 columns]

In [177]:
print(accuracy_score(y_test,pred)*100)

57.99999999999999
